name: 组播

on:
  schedule:
    - cron: '30 3,7,12,22 * * *'  # 每天下午运行
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write

jobs:
  filter-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install logging requests OrderedDict
    - name: Run 组播.py
      run: python ${{ github.workspace }}/py/iptv源收集检测/主频道/专享频道/py/组播/main.py

    - name: 提交更改
      run: |
        git config --local user.email "sh17611310186@mail.com"
        git config --local user.name "sh17611310186-lang"
        git add .
        # git commit *.txt -m "action: `date`"
        # git commit *.m3u -m "action: `date`"
        # git push -f
        git diff --quiet && git diff --staged --quiet || (git commit -m "action: `date`" && git push)
      env:
       TZ: Asia/Shanghai
